[workspace]
authors = ["Henry Addison <henryaddison@users.noreply.github.com>"]
channels = ["conda-forge", "nodefaults"]
name = "CPMGEM paper evaluation"
platforms = ["linux-64"]
version = "0.2.1"

[tasks]

[dependencies]
black = { version = "~=25.1.0" }
bottleneck = { version = "*" }
dask = { version = "*" }
flake8 = { version = "==6.1.0" }
iris = { version = "*" }
jupyterlab = { version = "*" }
metpy = { version = "*" }
nc-time-axis = { version = "==1.4.1" }
numpy = { version = "*" }
papermill = { version = "*" }
pint = { version = "*" }
pysteps = { version = "*" }
python = { version = "~=3.12.0" }
python-cdo = { version = "*" }
python-dotenv = { version = "*" }
scikit-learn = { version = "*" }
scipy = { version = "*" }
seaborn = { version = "*" }
typer = { version = "*" }
xarray = { version = "*" }

[pypi-dependencies]
mlde-analysis = { git = "https://github.com/henryaddison/mlde-analysis.git", rev = "v0.5.1" }
